tap "buo/cask-upgrade"
tap "homebrew/bundle"
tap "gemfury/tap"
# tap "hashicorp/tap"

brew "awscli"
brew "aws-sso-cli"
brew "bash"
brew "coreutils"
brew "curl"
brew "fury-cli"
brew "fzf"
brew "gawk"
brew "git"
brew "gpg2"
brew "hadolint"
brew "jq"
brew "kubectl"
brew "macvim"
brew "nvm"
brew "pinentry-mac"
brew "postgresql@15"
brew "libpq"
brew "rbenv"
brew "ruby-build"
brew "shellcheck"
# brew "terraform"
brew "tfsec"
brew "tfenv"
brew "tgenv"
brew "the_silver_searcher"
brew "tmux"
brew "unzip"
brew "watch"
brew "wget"
brew "zsh"
brew "yamllint"
brew "graphviz"
brew "gh"

cask "1password"
cask "font-consolas-for-powerline"
cask "font-dejavu-sans-mono-for-powerline"
cask "font-fira-code-nerd-font"
cask "font-noto-mono-for-powerline"
cask "font-powerline-symbols"
cask "font-roboto-mono-for-powerline"
cask "iterm2"
cask "iterm2"
cask "libreoffice"
cask "session-manager-plugin"
cask "spectacle"
cask "spotify"
cask "docker"
cask "workplace-chat"
cask "firefox"

# from tanda infra
tap "1password/tap"

brew "go"
brew "go-jsonnet"
brew "jq"
brew "jsonnet-bundler"
brew "watchman" # development only

cask "1password-cli"
cask "docker"

brew "circleci"
cask "insomnia"
